FROM ruby:3.2-alpine3.16

RUN gem install bundler:2.4.9

RUN apk update --no-cache && \
    apk add build-base postgresql-dev git nodejs yarn tzdata bash sqlite-dev npm gcompat && \
    mkdir -p /app

RUN npm install --global rollup

WORKDIR /app

COPY ./lib/ /app/lib/
COPY matestack-ui-vuejs.gemspec /app/
COPY Gemfile* /app/
RUN bundle install

COPY package.json yarn* /app/
RUN yarn install

RUN apk update && apk upgrade \
    && echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories \
    && apk add --no-cache \
    chromium=102.0.5005.182-r0 \
    nss=3.78.1-r0 \
    && rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

RUN apk add chromium-chromedriver=102.0.5005.182-r0

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
