FROM ruby:3.1-alpine3.16

RUN gem install bundler:2.4.9

RUN apk update --no-cache && \
    apk add build-base postgresql-dev git nodejs yarn tzdata bash sqlite-dev npm gcompat && \
    mkdir -p /app

RUN npm install --global rollup

WORKDIR /app

COPY ./lib/ /app/lib/
COPY matestack-ui-vuejs.gemspec /app/
COPY Gemfile* /app/
RUN bundle install

COPY package.json yarn* /app/
RUN yarn install
